/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_devin_cameratest_NativeInterface */

#ifndef _Included_com_devin_cameratest_NativeInterface
#define _Included_com_devin_cameratest_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_devin_cameratest_NativeInterface
 * Method:    cutNV21
 * Signature: ([BIIII[BII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_devin_cameratest_NativeInterface_cutNV21
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
